# Generated by Django 2.2 on 2021-04-27 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbc_app', '0002_checkoutaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_checkout_address', to='hbc_app.CheckoutAddress'),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('BS', 'Best Seller'), ('H', 'Holiday'), ('F', 'Featured')], max_length=3, null=True),
        ),
    ]
