# Generated by Django 2.2 on 2021-05-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbc_app', '0005_item_shirt_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shirt_color',
            field=models.CharField(blank=True, choices=[('Dark Heather', 'Dark Heather'), ('Heather Navy', 'Heather Navy'), ('Heather Indigo', 'Heather Indigo'), ('Heather Royal', 'Heather Royal'), ('Heather Sapphire', 'Heather Sapphire'), ('Heather Galapagos Blue', 'Heather Galapagos Blue'), ('Heather Seafoam', 'Heather Seafoam'), ('Heather Irish Green', 'Heather Irish Green'), ('Heather Military Green', 'Heather Military Green'), ('Heather Maroon', 'Heather Maroon'), ('Heather Purple', 'Heather Purple'), ('Heather Berry', 'Heather Berry'), ('Heather Helonica', 'Heather Helonica'), ('Heather Coral Silk', 'Heather Coral Silk'), ('Heather Orange', 'Heather Orange'), ('Heather Cardinal', 'Heather Cardinal'), ('Heather Red', 'Heather Red'), ('White', 'White'), ('None', 'None')], max_length=50, null=True),
        ),
    ]
