# Generated by Django 2.2 on 2021-05-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbc_app', '0007_auto_20210507_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutaddress',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
