# Generated by Django 2.2 on 2021-05-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbc_app', '0011_order_billing_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkout_address',
        ),
        migrations.DeleteModel(
            name='CheckoutAddress',
        ),
    ]
