# Generated by Django 2.2 on 2021-05-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbc_app', '0013_item_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
            ],
        ),
    ]
