# Generated by Django 2.2 on 2021-05-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbc_app', '0015_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
