# Generated by Django 2.2 on 2021-05-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbc_app', '0017_auto_20210512_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_process',
            field=models.BooleanField(default=False),
        ),
    ]
